### ISSUE TITLE
How do you create an environment?

### ISSUE THREAD

**Issue by ghost** [cowboyd/commonjs.rb#16]
The README says

```
env = CommonJS::Environment.new(:path => '/path/to/lib/dir')
```

But it doesn't explain what the path to lib directory is supposed to be a path to? What library? I've tried using the current directory but get an error.

```
1.9.3-p484 :024 >   env = CommonJS::Environment.new(:path => './')
TypeError: can't convert nil into String
    from /Users/mgwelch/.rvm/gems/ruby-1.9.3-p484/gems/commonjs-0.2.7/lib/commonjs/environment.rb:9:in `initialize'
    from /Users/mgwelch/.rvm/gems/ruby-1.9.3-p484/gems/commonjs-0.2.7/lib/commonjs/environment.rb:9:in `Pathname'
    from /Users/mgwelch/.rvm/gems/ruby-1.9.3-p484/gems/commonjs-0.2.7/lib/commonjs/environment.rb:9:in `block in initialize'
    from /Users/mgwelch/.rvm/gems/ruby-1.9.3-p484/gems/commonjs-0.2.7/lib/commonjs/environment.rb:9:in `map'
    from /Users/mgwelch/.rvm/gems/ruby-1.9.3-p484/gems/commonjs-0.2.7/lib/commonjs/environment.rb:9:in `initialize'
    from (irb):24:in `new'
    from (irb):24
    from /Users/mgwelch/.rvm/rubies/ruby-1.9.3-p484/bin/irb:12:in `<main>'
```

**Comment by MhdSyrwan** [comment]
You can find an example of a successful environment object creation here
https://github.com/cowboyd/commonjs.rb/blob/master/spec/spec_helper.rb

Example:

``` javascript
js = CommonJS::Environment.new(V8::Context.new, path: './node_modules')
```

**Comment by rogsmith** [comment]
Any ideas on how I can eval() js code now if I am using commonjs and therubyracer?

**Comment by bbozo** [comment]
What rogsmith said :)

**Comment by orta** [comment]
Looking at [the source](https://github.com/cowboyd/commonjs.rb/blob/master/lib/commonjs/environment.rb#L13) - this will just add them as modules into the existing runtime, you would re-use the `V8::Context.new` to eval things.
